In [1]:
import numpy as np
import torch 


In [3]:
t = torch.tensor([[1,2],[3,4.]])
t

tensor([[1., 2.],
        [3., 4.]])

In [4]:
t = torch.tensor([[1,2],[3,4.]],device="cuda:0")
t

tensor([[1., 2.],
        [3., 4.]], device='cuda:0')

In [6]:
t = torch.tensor([[1,2],[3,4.]],dtype=torch.float64)
t

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [8]:
t = torch.tensor([[1,2],[3,4.]],dtype=torch.float64,device="cuda:0")
t

tensor([[1., 2.],
        [3., 4.]], device='cuda:0', dtype=torch.float64)

In [9]:
t = torch.arange(0,10)
t

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
t = torch.zeros(100,10).to("cuda:0")
t

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],


In [11]:
t = torch.randn(100,10)
t

tensor([[-1.4327e-01,  5.8080e-01, -9.2699e-01, -1.3040e+00, -4.2049e-03,
         -5.2679e-01, -4.0099e-01, -3.3796e-01,  4.1200e-01, -5.1663e-01],
        [ 2.4819e-01, -1.3872e+00, -6.3199e-02, -4.5624e-01,  6.9960e-01,
          1.3640e-01,  6.4357e-01, -6.7758e-02,  3.8439e-01,  1.1077e+00],
        [-4.8724e-01,  1.3216e-01, -5.4600e-01,  2.4938e-01, -2.8076e-01,
         -7.8360e-01,  1.6042e+00,  3.1034e-01, -3.0905e-01, -1.6200e+00],
        [ 1.1727e+00, -1.3778e-01,  2.0990e-02, -6.8603e-01, -1.3180e-01,
          1.2514e+00,  6.1645e-01, -1.4099e-01, -2.4831e+00,  2.0677e-01],
        [-1.0156e+00,  2.0305e+00, -4.5313e-01,  3.6888e-01,  1.4681e+00,
          6.4781e-01,  5.5725e-01,  1.1010e+00,  1.8834e+00, -3.3264e-01],
        [ 1.4749e+00, -4.8508e-01,  9.0338e-01,  3.6480e-01,  5.5803e-02,
         -7.9836e-01,  6.7896e-01, -1.3267e+00,  1.9676e-01, -1.2773e+00],
        [ 1.5046e-02, -8.7756e-01, -3.1212e-01,  1.4016e+00, -1.1636e+00,
         -5.0024e-01,  7.8459e-0

In [15]:
t.size()

torch.Size([100, 10])

In [19]:
t = torch.tensor([[1,2],[3,4.]])
t = t.numpy()
t

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [21]:
t = torch.tensor([[1,2],[3,4.]],device="cuda:0")
t = t.to("cpu:0")
t = t.numpy()
t

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [29]:
t = torch.tensor([[2,5,9],[4,5,6.]])
x = t[t<3]
x

tensor([2.])

In [31]:
v = torch.tensor([1,2,3.])
w = torch.tensor([0,10,20.])

m = v+w
m

tensor([ 1., 12., 23.])

In [34]:
n = v-w
n

tensor([  1.,  -8., -17.])

In [35]:
mu = v*m
mu

tensor([ 1., 24., 69.])

In [41]:
x = torch.randn(100,10)
y = x*2 + torch.abs(x)
x

tensor([[ 1.3103e+00, -1.0390e+00, -7.6805e-01,  1.0658e+00, -9.2028e-01,
         -5.0219e-01, -1.4951e-01,  1.2346e+00,  1.8419e+00,  1.9752e+00],
        [-9.5819e-01, -1.0206e+00,  1.2814e+00, -1.4326e+00,  1.7298e+00,
         -5.8740e-01, -1.8861e-01,  3.1076e-01,  3.2056e-01,  2.2039e-01],
        [ 1.4974e+00,  7.7451e-01, -1.0369e+00, -3.4253e-01,  1.2490e+00,
         -3.5241e-01, -4.6002e-02,  6.6380e-01, -1.3750e+00,  2.0542e-01],
        [ 1.0162e+00, -3.5495e-04,  7.9454e-01, -2.3328e-02, -6.1012e-01,
         -2.4708e+00,  1.9815e+00, -1.7427e-01,  1.5532e+00, -8.5991e-01],
        [ 1.0119e+00, -1.7140e-02, -1.0535e+00, -1.1436e+00, -9.1391e-01,
         -2.0535e+00, -3.6777e-01, -1.1485e+00, -1.6344e+00,  1.1202e+00],
        [ 4.1739e-01, -1.1816e+00,  7.3895e-01, -6.0401e-01,  3.3540e-01,
          6.3000e-01, -8.5490e-01,  5.9051e-01, -7.1932e-01, -1.9281e+00],
        [-1.2524e-01, -1.0458e+00,  2.2881e-01, -1.0997e-01, -5.7292e-02,
          2.0984e-01,  9.4429e-0

In [42]:
y

tensor([[ 3.9308e+00, -1.0390e+00, -7.6805e-01,  3.1974e+00, -9.2028e-01,
         -5.0219e-01, -1.4951e-01,  3.7038e+00,  5.5256e+00,  5.9255e+00],
        [-9.5819e-01, -1.0206e+00,  3.8441e+00, -1.4326e+00,  5.1893e+00,
         -5.8740e-01, -1.8861e-01,  9.3229e-01,  9.6167e-01,  6.6116e-01],
        [ 4.4923e+00,  2.3235e+00, -1.0369e+00, -3.4253e-01,  3.7471e+00,
         -3.5241e-01, -4.6002e-02,  1.9914e+00, -1.3750e+00,  6.1626e-01],
        [ 3.0485e+00, -3.5495e-04,  2.3836e+00, -2.3328e-02, -6.1012e-01,
         -2.4708e+00,  5.9444e+00, -1.7427e-01,  4.6597e+00, -8.5991e-01],
        [ 3.0356e+00, -1.7140e-02, -1.0535e+00, -1.1436e+00, -9.1391e-01,
         -2.0535e+00, -3.6777e-01, -1.1485e+00, -1.6344e+00,  3.3606e+00],
        [ 1.2522e+00, -1.1816e+00,  2.2169e+00, -6.0401e-01,  1.0062e+00,
          1.8900e+00, -8.5490e-01,  1.7715e+00, -7.1932e-01, -1.9281e+00],
        [-1.2524e-01, -1.0458e+00,  6.8643e-01, -1.0997e-01, -5.7292e-02,
          6.2951e-01,  2.8329e+0

In [44]:
m = torch.mean(x)
m

tensor(-0.0077)

In [45]:
x.mean()

tensor(-0.0077)

In [47]:
m_value = m.item()
m_value

-0.007659450639039278

In [52]:
m2 = x.mean(0)
m2

tensor([ 0.0009,  0.0035, -0.0075,  0.0738,  0.1212, -0.1462, -0.0469, -0.0238,
         0.0301, -0.0818])

In [61]:
x1 = torch.tensor([[1,2],[3,4]])
x2 = torch.tensor([[10,20,30],[40,50,60]])
x3 = x1.view(-1,4)
x3

tensor([[1, 2, 3, 4]])

In [67]:
x4 = x2.t()
x4

tensor([[10, 40],
        [20, 50],
        [30, 60]])

In [81]:
x5 = torch.cat([x1,x4],dim=0)
x5

tensor([[ 1,  2],
        [ 3,  4],
        [10, 40],
        [20, 50],
        [30, 60]])

In [82]:
hwc_img_data = torch.rand(100,64,32,3)
hwc_img_data


tensor([[[[0.0490, 0.6140, 0.5116],
          [0.2062, 0.2109, 0.4988],
          [0.0173, 0.4670, 0.3653],
          ...,
          [0.8457, 0.6040, 0.2978],
          [0.8010, 0.3356, 0.2616],
          [0.4050, 0.4577, 0.6944]],

         [[0.6309, 0.5064, 0.2246],
          [0.7383, 0.6761, 0.1965],
          [0.0288, 0.2872, 0.9643],
          ...,
          [0.8105, 0.5103, 0.4745],
          [0.5860, 0.1592, 0.2650],
          [0.3218, 0.6456, 0.2880]],

         [[0.9769, 0.6556, 0.7402],
          [0.8235, 0.3038, 0.8202],
          [0.8879, 0.7536, 0.3367],
          ...,
          [0.1810, 0.4222, 0.6768],
          [0.7275, 0.8946, 0.1142],
          [0.0680, 0.1471, 0.9112]],

         ...,

         [[0.6607, 0.6548, 0.3548],
          [0.1524, 0.4097, 0.1608],
          [0.7504, 0.6505, 0.5833],
          ...,
          [0.7316, 0.9056, 0.9838],
          [0.0838, 0.9783, 0.9983],
          [0.5727, 0.4251, 0.3723]],

         [[0.4892, 0.9260, 0.4116],
          [0.4795

In [83]:
chw_img_data = hwc_img_data.transpose(1,2).transpose(1,3)
chw_img_data

tensor([[[[0.0490, 0.2062, 0.0173,  ..., 0.8457, 0.8010, 0.4050],
          [0.6309, 0.7383, 0.0288,  ..., 0.8105, 0.5860, 0.3218],
          [0.9769, 0.8235, 0.8879,  ..., 0.1810, 0.7275, 0.0680],
          ...,
          [0.6607, 0.1524, 0.7504,  ..., 0.7316, 0.0838, 0.5727],
          [0.4892, 0.4795, 0.1580,  ..., 0.4748, 0.4993, 0.8927],
          [0.6816, 0.5847, 0.0768,  ..., 0.8389, 0.4627, 0.6344]],

         [[0.6140, 0.2109, 0.4670,  ..., 0.6040, 0.3356, 0.4577],
          [0.5064, 0.6761, 0.2872,  ..., 0.5103, 0.1592, 0.6456],
          [0.6556, 0.3038, 0.7536,  ..., 0.4222, 0.8946, 0.1471],
          ...,
          [0.6548, 0.4097, 0.6505,  ..., 0.9056, 0.9783, 0.4251],
          [0.9260, 0.1462, 0.7828,  ..., 0.8193, 0.6457, 0.9414],
          [0.1561, 0.7242, 0.8258,  ..., 0.1892, 0.3589, 0.7896]],

         [[0.5116, 0.4988, 0.3653,  ..., 0.2978, 0.2616, 0.6944],
          [0.2246, 0.1965, 0.9643,  ..., 0.4745, 0.2650, 0.2880],
          [0.7402, 0.8202, 0.3367,  ..., 0

In [93]:
m = torch.randn(100,10)
v= torch.randn(1,10)


In [90]:
v2 = torch.mv(m,v)
v2

tensor([ 2.0874,  7.2410, -0.7615, -2.4083,  0.1406,  3.3513, -0.5066, -6.6631,
         2.4850, -0.0561,  1.2076,  1.2809, -0.8319,  4.7842,  5.3100,  1.7299,
        -1.0451, -4.7133, -2.6199, -1.2362, -0.4435,  2.0122, -4.0903,  0.3113,
        -6.9171, -7.7240, -6.2336, -5.9490, -1.5062, -1.2306,  5.5276,  1.6765,
        -1.8933, -6.1617, -1.9327,  2.3866, -1.2477,  2.5395,  3.9813,  1.0884,
        -1.1251,  3.1088, -2.5147,  0.1075, -5.5407,  3.3442,  0.5643,  1.8347,
         5.6891,  0.7747,  1.9834,  4.6407, -1.5187,  0.5960,  0.9838,  0.6077,
        -2.8566,  4.6395, -1.4474, -2.1155, -0.1572, -4.8646,  0.8897, -5.1707,
         2.8496,  0.5241,  1.1454, -1.0220,  2.5538,  0.0260,  1.2688, -3.9189,
        -2.8926, -4.1043,  2.4102,  4.1215,  1.7164, -1.9254, -1.4344,  2.4568,
         1.1332, -1.6752,  0.9607,  3.2160,  1.8694,  0.3351, -3.6077, -4.8895,
        -1.4567,  1.2214,  3.6465, -1.5685, -3.6474,  2.2414, -1.8639, -4.2132,
         4.0737,  3.2945,  0.7238, -2.26

In [94]:
v3 = torch.mm(m,v.t())
v3

tensor([[ 2.4101e+00],
        [-4.7496e+00],
        [-1.8626e+00],
        [-1.0694e-01],
        [-2.1344e+00],
        [ 3.0590e+00],
        [ 7.7740e-01],
        [-1.4811e+00],
        [ 4.3939e-01],
        [ 1.1018e+00],
        [ 1.4014e+00],
        [ 2.3824e+00],
        [ 1.8623e+00],
        [ 2.3906e+00],
        [ 1.4556e+00],
        [-2.7715e+00],
        [-2.5138e-01],
        [-2.0608e-01],
        [ 1.2667e-02],
        [ 3.7405e+00],
        [-5.8112e-01],
        [-9.3864e-01],
        [ 4.2465e+00],
        [-2.3026e+00],
        [-2.5576e+00],
        [ 2.0657e+00],
        [-2.5146e+00],
        [ 1.3509e+00],
        [-1.9736e+00],
        [ 4.1808e-01],
        [ 1.8592e+00],
        [-3.3008e-01],
        [-1.3558e+00],
        [-5.8365e-04],
        [-1.1360e+00],
        [ 5.8987e-01],
        [ 2.7130e+00],
        [-1.7854e+00],
        [ 2.8299e+00],
        [ 6.1998e+00],
        [ 1.4173e+00],
        [ 2.5830e+00],
        [ 1.4157e+00],
        [ 1

In [95]:
u,s,v = torch.svd(m)

In [96]:
u

tensor([[-0.1234, -0.0203,  0.1078, -0.0638, -0.2598, -0.0649, -0.0903,  0.0095,
         -0.0166,  0.1631],
        [-0.1310, -0.0330,  0.0696, -0.0225, -0.0675,  0.1633,  0.2467,  0.0161,
         -0.0254, -0.0593],
        [ 0.1126, -0.0032,  0.0370, -0.0113, -0.0114,  0.1241,  0.0649,  0.1745,
          0.0583, -0.0277],
        [ 0.0471,  0.0938, -0.1137,  0.0559,  0.0614,  0.0304, -0.0506, -0.1320,
         -0.0775,  0.0371],
        [-0.1561,  0.0074, -0.0984, -0.2861,  0.0522, -0.1261, -0.0133,  0.0248,
         -0.0307, -0.1594],
        [-0.0564, -0.0848, -0.0353, -0.0268,  0.1471, -0.2299,  0.0187,  0.1413,
          0.0125,  0.1288],
        [ 0.0467, -0.0474, -0.1896,  0.0010,  0.0647,  0.0903,  0.0101, -0.1319,
          0.0158,  0.0747],
        [ 0.0253, -0.0253, -0.1961, -0.0194, -0.0938,  0.2917, -0.0046, -0.0554,
          0.1418,  0.0188],
        [ 0.0619, -0.0118, -0.2306,  0.0313,  0.0533,  0.0302,  0.0498, -0.0345,
          0.1322,  0.0244],
        [-0.0523, -

In [97]:
s

tensor([13.3688, 11.8904, 11.7182, 11.0257,  9.9149,  9.5747,  9.0094,  8.3639,
         7.8927,  7.5221])

In [98]:
v

tensor([[ 0.1061, -0.3735,  0.1667, -0.3887,  0.2378, -0.3136, -0.1101,  0.3515,
          0.2842, -0.5468],
        [ 0.2554,  0.2130, -0.2275,  0.4624,  0.3645, -0.4588, -0.2723, -0.3207,
         -0.1330, -0.2928],
        [-0.3903, -0.1385, -0.4824,  0.2160,  0.1381,  0.4085,  0.2786, -0.1160,
          0.2682, -0.4473],
        [ 0.0274,  0.3311,  0.1253, -0.5277,  0.0841, -0.0796,  0.4809, -0.5059,
         -0.1871, -0.2446],
        [ 0.0759,  0.3575, -0.1697,  0.0784, -0.7581, -0.2811,  0.0853,  0.1643,
          0.2428, -0.2907],
        [-0.5743, -0.4306, -0.1160, -0.0223, -0.2313, -0.4817,  0.0092, -0.1399,
         -0.4053,  0.0365],
        [ 0.4701, -0.4982, -0.2899, -0.1805, -0.2727,  0.0707, -0.1355, -0.5069,
          0.2106,  0.1233],
        [-0.2542, -0.0381,  0.5033,  0.2628,  0.0292, -0.2231,  0.1097, -0.3549,
          0.6300,  0.1611],
        [ 0.3816, -0.3084,  0.0707,  0.3644,  0.0278, -0.1438,  0.7296,  0.2074,
         -0.1487,  0.0509],
        [ 0.0599, -

In [142]:
x = torch.randn(100,3)
x

tensor([[-5.2834e-03, -1.3294e+00,  8.6417e-01],
        [-8.0044e-01,  1.0152e+00, -4.6532e-01],
        [ 7.5590e-01, -1.0440e+00, -5.2295e-01],
        [ 2.0302e-02,  1.0525e+00, -2.8658e+00],
        [-5.0456e-01, -2.3885e+00, -6.2088e-02],
        [ 9.4288e-01,  7.9127e-01, -2.4011e-02],
        [ 8.0682e-01,  2.4584e-01,  1.0002e+00],
        [-2.8220e-01, -1.1513e+00,  2.5338e-01],
        [-3.4652e-01,  7.8560e-01,  4.5244e-01],
        [-1.2847e+00,  1.1528e+00, -3.4614e-01],
        [ 5.3863e-01, -7.8429e-01, -6.0077e-01],
        [-6.7141e-01,  2.0363e+00,  1.1324e-01],
        [ 2.9215e-01,  1.1150e+00,  6.9528e-01],
        [ 2.4913e-01,  2.3649e-01, -2.4209e+00],
        [ 1.9081e+00, -6.5543e-01, -9.7973e-01],
        [-8.3107e-01,  4.1463e-01,  1.9123e+00],
        [ 7.5111e-01,  2.2112e-01, -4.2122e-01],
        [ 1.4173e+00, -2.4712e-01,  1.1819e+00],
        [-2.2724e+00, -1.7619e+00, -1.3311e+00],
        [-2.4150e-01,  2.4777e-01,  5.4191e-01],
        [-3.4579e-01

In [143]:
a = torch.tensor([1,2,3.],requires_grad=True)
a

tensor([1., 2., 3.], requires_grad=True)

tensor([1., 2., 3.], requires_grad=True)

In [145]:
 y = torch.mv(x,a)
y

tensor([-0.0716, -0.1660, -2.9010, -6.4721, -5.4678,  2.4534,  4.2990, -1.8247,
         2.5820, -0.0175, -2.8323,  3.7409,  4.6080, -6.5405, -2.3420,  5.7350,
        -0.0703,  4.4689, -9.7893,  1.8798, -2.9747, -3.6885, -7.2359,  2.4561,
         1.2443,  7.0678,  2.3766, -3.6919, -2.4682, -0.6605,  0.2107, -0.8022,
        -5.3903,  4.7818, -2.8530,  0.4823,  0.7564, -1.6869, -3.1655, -2.0072,
        -1.7165,  2.0421, -4.8897, -3.7927, -0.2755,  3.7711,  1.2550, -1.0508,
         5.5527,  4.4072,  3.3619, -0.0160, -4.3079,  1.4849,  5.7630,  6.6150,
        -1.7394,  0.6378, -5.5675,  2.0625, -9.5054,  5.5568,  2.1740, -0.6365,
         0.0607, -3.1848, -3.6907, -0.5133, -2.0967,  1.8874, -3.4275, -2.0443,
         4.8232, -3.6950, -3.2276, -7.5826, -2.3281,  2.7334, -1.2338,  2.4291,
        -0.9447, -2.3344, -4.9337, -3.2302,  2.1648, -1.5358,  0.1805, -4.4919,
        -5.1220, -2.6385, -1.3878, -1.3949, -7.5196, -2.9019,  3.3290, -4.1744,
        -3.0234, -5.9850,  2.3965, -0.91

In [146]:
o = y.sum()
o

tensor(-80.3395, grad_fn=<SumBackward0>)

In [147]:
o.backward()


In [122]:
a.grad != x.sum(0)

tensor([ True, False,  True])

In [120]:
x.grad is None

True

In [148]:
o

tensor(-80.3395, grad_fn=<SumBackward0>)